DROP TABLE RepSellsArea;
COMMIT;
DROP TABLE RepSellsProduct;
COMMIT;
DROP TABLE AreaSellsProduct;
COMMIT;


DELETE FROM Rep WHERE RID=11111;
COMMIT;
DELETE FROM Area WHERE ARID=’WDT’;
COMMIT;
DELETE FROM Product WHERE PRID=1;
COMMIT;
