CREATE TABLE Rep (RID INT NOT NULL, RNAME VARCHAR(25), RAGE INT, SALARY INT, PRIMARY KEY(RID));

CREATE TABLE Area (ARID VARCHAR(3) NOT NULL, ANAME VARCHAR(20), CITY VARCHAR(20), BUDGET DOUBLE(10, 2), PRIMARY KEY(ARID));

CREATE TABLE Product(PRID INTEGER NOT NULL, PNAME VARCHAR(20), PDESC VARCHAR(20), PRICE DOUBLE(6, 2), PRIMARY KEY(PRID));

CREATE TABLE RepSellsArea (RID INTEGER NOT NULL, ARID VARCHAR(3) NOT NULL, hours INTEGER, revenue DOUBLE(8, 2), FOREIGN KEY(RID) REFERENCES Rep(RID), FOREIGN KEY (ARID) REFERENCES Area(ARID), PRIMARY KEY(RID, ARID));

CREATE TABLE RepSellsProduct(RID INTEGER NOT NULL, PRID INTEGER NOT NULL, hours INTEGER, revenue DOUBLE(8, 2), FOREIGN KEY(RID) REFERENCES Rep(RID), FOREIGN KEY(PRID) REFERENCES Product(PRID), PRIMARY KEY(RID, PRID));

CREATE TABLE AreaSellsProduct(ARID VARCHAR(3) NOT NULL, PRID INTEGER NOT NULL, hours INTEGER NOT NULL, revenue DOUBLE(8, 2), FOREIGN KEY(ARID) REFERENCES Area(Arid), FOREIGN KEY(PRID) REFERENCES Product(PRID), PRIMARY KEY(ARID, PRID));
